test:
  workers:
    number: 16
  rounds:
    - label: Create a car .
      txDuration: 30
      rateControl:
        type: fixed-rate
        opts:
          tps: 1000
          # transactionLoad: 2000
      workload:
        module: benchmarks/fabcar/createCar.js
