test:
  workers:
    type: local
    number: 16
  rounds:
    - label: initLedger 
      txNumber: 1
      rateControl:
          type: fixed-rate
          opts:
            tps: 1
      workload:
        module: benchmarks/electronic-health-record/initLedger.js

    - label: common
      txNumber: 10000
      rateControl:
          type: fixed-rate
          opts:
            tps: 10
      workload:
        module: benchmarks/electronic-health-record/common.js

