test:
    name: basic-contract-benchmark
    description: test benchmark
    workers:
      number: 5
    rounds:
      - label: readAsset
        description: Read asset benchmark
        txDuration: 30
        rateControl:
          type: fixed-load
          opts:
            transactionLoad: 2
        workload:
          module: benchmarks/basic/readAsset.js
          arguments:
            assets: 10
            contractId: basic
